/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.entrega;

import br.com.dal_connexao.ModuloConexao;
import br.com.dal_connexao.ModuloConexao;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class EntregasCadastro extends javax.swing.JInternalFrame {

    int i = 0;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    PreparedStatement executa = null;

    public EntregasCadastro() throws SQLException {

        initComponents();
        conexao = ModuloConexao.conector();
        pegarCliente();
        pegarMotorista();

    }

    public void pegarCliente() {
        try {
            String nomes;

            String sql = "SELECT * FROM cliente";
            st = conexao.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                nomes = rs.getString("nome");
                cliente.addItem(nomes);
            }
            rs.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(EntregasCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void pegarMotorista() throws SQLException {
        try {
            String nomes;

            String sql = "SELECT * FROM cadastrologin";
            st = conexao.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                nomes = rs.getString("nomeentregador");
                motorista.addItem(nomes);
            }
            rs.close();
            st.close();
        }catch (SQLException ex) {
            Logger.getLogger(EntregasCadastro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    public void inserir() {
        String sql = "insert into entregas(data, endereco, nome, notafisca, saida, volume) values(?, ?, ?, ?, ?, ?)";

        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, txdata.getText());
            pst.setString(2, txendereco.getText());
            pst.setString(3, String.valueOf(cliente.getSelectedItem()));
            pst.setString(4, txnt.getText());
            pst.setString(5, String.valueOf(motorista.getSelectedItem()));
            pst.setInt(6, Integer.parseInt(txvolume.getText()));

            pst.executeUpdate();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txendereco = new javax.swing.JTextField();
        lblocal = new javax.swing.JLabel();
        lbnt = new javax.swing.JLabel();
        txnt = new javax.swing.JTextField();
        lbvoloume = new javax.swing.JLabel();
        lbdata = new javax.swing.JLabel();
        txvolume = new javax.swing.JTextField();
        txdata = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbnome = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsalvar = new javax.swing.JTable();
        lbendereco = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cliente = new javax.swing.JComboBox<>();
        motorista = new javax.swing.JComboBox<>();

        lblocal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblocal.setText("Motorista");

        lbnt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbnt.setText("Nota Fiscal :");

        lbvoloume.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbvoloume.setText("Volume :");

        lbdata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbdata.setText("Data da Emissão :");

        txdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdataActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbnome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbnome.setText("Nome do Cliente :");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblsalvar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Nome", "Endereço", "Saida", "NF", "Volume"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblsalvar);

        lbendereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbendereco.setText("Endereço :");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });

        motorista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoristaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbdata)
                                .addGap(23, 23, 23)
                                .addComponent(txdata, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbendereco)
                                .addGap(59, 59, 59)
                                .addComponent(txendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblocal)
                                .addGap(63, 63, 63)
                                .addComponent(motorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnt)
                                .addGap(53, 53, 53)
                                .addComponent(txnt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbvoloume)
                                .addGap(69, 69, 69)
                                .addComponent(txvolume, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnome)
                                .addGap(18, 18, 18)
                                .addComponent(cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbdata))
                            .addComponent(txdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lbnome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbendereco))
                            .addComponent(txendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblocal)
                            .addComponent(motorista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbnt))
                            .addComponent(txnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbvoloume))
                            .addComponent(txvolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(217, 217, 217)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txdataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String data, nomec, endereco, locals, notaf, volume;
        String sinal = null;
        data = txdata.getText();
        nomec = String.valueOf(cliente.getSelectedItem());
        endereco = txendereco.getText();
        locals = String.valueOf(motorista.getSelectedItem());
        notaf = txnt.getText();
        volume = txvolume.getText();
        tblsalvar.setValueAt(data, i, 0);
        tblsalvar.setValueAt(nomec, i, 1);
        tblsalvar.setValueAt(endereco, i, 2);
        tblsalvar.setValueAt(locals, i, 3);
        tblsalvar.setValueAt(notaf, i, 4);
        tblsalvar.setValueAt(volume, i, 5);
        i++;
        inserir();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        MenuFinal voltarMenu = new MenuFinal();
        voltarMenu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        inserir();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void motoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoristaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbendereco;
    private javax.swing.JLabel lblocal;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbnt;
    private javax.swing.JLabel lbvoloume;
    private javax.swing.JComboBox<String> motorista;
    private javax.swing.JTable tblsalvar;
    private javax.swing.JTextField txdata;
    private javax.swing.JTextField txendereco;
    private javax.swing.JTextField txnt;
    private javax.swing.JTextField txvolume;
    // End of variables declaration//GEN-END:variables
}
