/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.entrega;

/**
 *
 * @author ricar
 */
public class MenuFinal extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuFinal
     */
    public MenuFinal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JDesktopPane();
        vender = new javax.swing.JButton();
        comprar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 745, 582));

        vender.setBackground(new java.awt.Color(0, 102, 204));
        vender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        vender.setForeground(new java.awt.Color(255, 255, 255));
        vender.setText("Lista de Entregas");
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });
        getContentPane().add(vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 370, 125));

        comprar.setBackground(new java.awt.Color(0, 102, 204));
        comprar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        comprar.setForeground(new java.awt.Color(255, 255, 255));
        comprar.setText("Cadastrar Entregas");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        getContentPane().add(comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 125));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
        Entregalista mostraLista = new Entregalista();
         Panel1.add(mostraLista);
         mostraLista.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_venderActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        EntregasCadastro cadastrarPlanilha = new EntregasCadastro();
        Panel1.add(cadastrarPlanilha);
        cadastrarPlanilha.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_comprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Panel1;
    private javax.swing.JButton comprar;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
