/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.entrega;

import br.com.compra.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hiury
 */
public class telaEntregas extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaVenda
     */
   
    public telaEntregas() {
       
            initComponents();
            
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosEntrega = new javax.swing.JButton();
        cadEntrega = new javax.swing.JButton();
        telaEntrega = new javax.swing.JDesktopPane();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dadosEntrega.setBackground(new java.awt.Color(0, 102, 204));
        dadosEntrega.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dadosEntrega.setForeground(new java.awt.Color(255, 255, 255));
        dadosEntrega.setText("Dados Entregas");
        dadosEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosEntregaActionPerformed(evt);
            }
        });
        getContentPane().add(dadosEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, 374, 125));

        cadEntrega.setBackground(new java.awt.Color(0, 102, 204));
        cadEntrega.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadEntrega.setForeground(new java.awt.Color(255, 255, 255));
        cadEntrega.setText("Cadastro Entregas");
        cadEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEntregaActionPerformed(evt);
            }
        });
        getContentPane().add(cadEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 125));

        javax.swing.GroupLayout telaEntregaLayout = new javax.swing.GroupLayout(telaEntrega);
        telaEntrega.setLayout(telaEntregaLayout);
        telaEntregaLayout.setHorizontalGroup(
            telaEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        telaEntregaLayout.setVerticalGroup(
            telaEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        getContentPane().add(telaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 747, 582));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosEntregaActionPerformed
        DadosEntrega entrega = new DadosEntrega();
        telaEntrega.add(entrega);
        entrega.setVisible(true);       
    }//GEN-LAST:event_dadosEntregaActionPerformed

    private void cadEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEntregaActionPerformed
        CadEntrega entrega = new CadEntrega();
        telaEntrega.add(entrega);
        entrega.setVisible(true);
      
    }//GEN-LAST:event_cadEntregaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadEntrega;
    private javax.swing.JButton dadosEntrega;
    private javax.swing.JDesktopPane telaEntrega;
    // End of variables declaration//GEN-END:variables
}
